# SOPS configuration for OpenClaw secrets management
# This file defines which JSON keys should be encrypted

creation_rules:
  # All .enc files in the data directory
  - path_regex: .*\.enc$
    age: age1yhhu30v48zpsdenm82dc9s2k7w7zcw3vqktlf9fqxqg0qhrz33kq6e9x4h

    # Only encrypt these sensitive key patterns (regex on JSON path)
    encrypted_regex: >-
      ^(
        token|
        key|
        password|
        secret|
        apiKey|
        botToken|
        appToken|
        credential|
        access|
        refresh|
        sessionKey|
        cookie|
        privateKey
      )$

    # Preserve JSON structure
    unencrypted_suffix: _unencrypted
